set timeout -1
spawn vpnc
expect "Enter IPSec gateway address:";
send -- "$env(IPSEC_GATEWAY)\r";
expect "Enter IPSec ID for $env(IPSEC_GATEWAY):";
send -- "$env(IPSEC_ID)\r";
expect "Enter IPSec secret for $env(IPSEC_ID)@$env(IPSEC_GATEWAY):";
send -- "$env(IPSEC_SECRET)\r";
expect "Enter username for $env(IPSEC_GATEWAY):";
send -- "$env(USER_NAME)\r";
expect "Enter password for $env(USER_NAME)@$env(IPSEC_GATEWAY):";
send -- "$env(USER_PASSWORD)\r";
expect "$ ";
